<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Users Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            font-size: 12px;
            line-height: 1.4;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 15px;
        }

        .header h1 {
            margin: 0;
            color: #333;
            font-size: 24px;
        }

        .header p {
            margin: 5px 0;
            color: #666;
        }

        .summary-section {
            background: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 25px;
        }

        .summary-title {
            font-size: 16px;
            font-weight: bold;
            color: #333;
            margin-bottom: 10px;
        }

        .summary-grid {
            display: table;
            width: 100%;
        }

        .summary-row {
            display: table-row;
        }

        .summary-cell {
            display: table-cell;
            padding: 5px 10px;
            border-bottom: 1px solid #ddd;
        }

        .summary-cell:first-child {
            font-weight: bold;
            width: 30%;
        }

        .section {
            margin-bottom: 30px;
        }

        .section-title {
            font-size: 16px;
            font-weight: bold;
            color: #333;
            margin-bottom: 15px;
            padding: 8px 0;
            border-bottom: 1px solid #333;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }

        tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        .footer {
            margin-top: 40px;
            padding-top: 15px;
            border-top: 1px solid #ddd;
            text-align: center;
            color: #666;
            font-size: 10px;
        }

        .no-data {
            text-align: center;
            color: #666;
            font-style: italic;
            padding: 20px;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>{{ ucfirst($report_type) }} Users Report</h1>
        <p>AuthenticityHub - Admin Report System</p>
        <p>Generated on: {{ $generated_at->format('F j, Y \a\t g:i A') }}</p>
    </div>

    <div class="summary-section">
        <div class="summary-title">Report Summary</div>
        <div class="summary-grid">
            <div class="summary-row">
                <div class="summary-cell">Report Type:</div>
                <div class="summary-cell">{{ ucfirst($report_type) }} Report</div>
            </div>
            <div class="summary-row">
                <div class="summary-cell">Date Range:</div>
                <div class="summary-cell">{{ $date_from }} to {{ $date_to }}</div>
            </div>
            <div class="summary-row">
                <div class="summary-cell">User Type Filter:</div>
                <div class="summary-cell">{{ $user_type ? ucfirst($user_type) . ' Users' : 'All Users' }}</div>
            </div>
            <div class="summary-row">
                <div class="summary-cell">Total Users:</div>
                <div class="summary-cell">{{ $total_users }}</div>
            </div>
            <div class="summary-row">
                <div class="summary-cell">Public Users:</div>
                <div class="summary-cell">{{ $total_public_users }}</div>
            </div>
            <div class="summary-row">
                <div class="summary-cell">Agencies:</div>
                <div class="summary-cell">{{ $total_agencies }}</div>
            </div>
            <div class="summary-row">
                <div class="summary-cell">Generated By:</div>
                <div class="summary-cell">{{ $generated_by }}</div>
            </div>
        </div>
    </div>

    @if ($report_type === 'detailed')
        @if ($public_users->count() > 0)
            <div class="section">
                <div class="section-title">Public Users ({{ $public_users->count() }})</div>
                <table>
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Username</th>
                            <th>Email</th>
                            <th>Phone</th>
                            <th>Created Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($public_users as $user)
                            <tr>
                                <td>{{ $user->UserID }}</td>
                                <td>{{ $user->UserName }}</td>
                                <td>{{ $user->UserEmail }}</td>
                                <td>{{ $user->UserPhoneNum ?? 'N/A' }}</td>
                                <td>{{ $user->created_at ? $user->created_at->format('m/d/Y h:i A') : 'N/A' }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        @endif

        @if ($agencies->count() > 0)
            <div class="section">
                <div class="section-title">Agencies ({{ $agencies->count() }})</div>
                <table>
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Agency Name</th>
                            <th>Username</th>
                            <th>Email</th>
                            <th>Phone</th>
                            <th>Type</th>
                            <th>Created Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($agencies as $agency)
                            <tr>
                                <td>{{ $agency->AgencyID }}</td>
                                <td>{{ $agency->AgencyName }}</td>
                                <td>{{ $agency->AgencyUserName }}</td>
                                <td>{{ $agency->AgencyEmail }}</td>
                                <td>{{ $agency->AgencyPhoneNum ?? 'N/A' }}</td>
                                <td>{{ $agency->AgencyType ?? 'Default' }}</td>
                                <td>{{ $agency->created_at ? $agency->created_at->format('m/d/Y h:i A') : 'N/A' }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        @endif

        @if ($public_users->count() === 0 && $agencies->count() === 0)
            <div class="no-data">
                No users found for the specified criteria and date range.
            </div>
        @endif
    @endif

    <div class="footer">
        <p>This report was generated automatically by the AuthenticityHub Admin System.</p>
        <p>Report contains {{ $total_users }} user(s) for the period {{ $date_from }} to {{ $date_to }}.</p>
    </div>
</body>

</html>
